name: Update admin-shared submodule

on:
  repository_dispatch:
    types: [update-submodule]
  workflow_dispatch:  # Cho phép test thủ công

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Token mặc định là đủ

      - name: Update submodule
        run: |
            git config user.name "github-actions"
            git config user.email "actions@github.com"

            # Update submodule directly to latest commit of main branch
            cd admin-shared
            git fetch origin main
            git checkout origin/main
            cd ..

            git add admin-shared
            git commit -m "Auto-update from admin-shared" || echo "No changes"
            git push
